/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A platform-agnostic contract describing a design system component.
 */
export interface ComponentContract {
  id: string;
  $schema?: string;
  version: string;
  displayName: string;
  description?: string;
  status: "draft" | "alpha" | "beta" | "stable" | "deprecated" | "removed";
  deprecation?: {
    reason: string;
    replacedBy: string;
    removeAfterVersion?: string;
  };
  /**
   * @minItems 1
   */
  platforms: ["web" | "ios" | "android" | "macos" | "windows", ...("web" | "ios" | "android" | "macos" | "windows")[]];
  tokens?: {
    color?: {
      [k: string]: string;
    };
    typography?: {
      [k: string]: string;
    };
    spacing?: {
      [k: string]: string;
    };
    border?: {
      [k: string]: string;
    };
    shadow?: {
      [k: string]: string;
    };
    motion?: {
      [k: string]: string;
    };
  };
  props: {
    [k: string]: PropDefinition;
  };
  variants?: {
    id: string;
    displayName: string;
    description?: string;
    props: {
      [k: string]: unknown;
    };
  }[];
  states?: ("default" | "hover" | "focus" | "active" | "disabled" | "loading" | "error" | "success" | "empty")[];
  behavior?: {
    focusable?: boolean;
    pressable?: boolean;
    scrollable?: boolean;
    draggable?: boolean;
    dismissable?: boolean;
    keyboardShortcuts?: {
      key: string;
      action: string;
    }[];
  };
  accessibility?: {
    role?: string;
    labelSource?: "prop" | "slot" | "aria-label" | "aria-labelledby" | "native";
    requiredAria?: string[];
    focusManagement?: "none" | "self" | "trap" | "restore";
    wcagLevel?: "A" | "AA" | "AAA";
  };
  composition?: {
    slots?: {
      [k: string]: {
        description?: string;
        required?: boolean;
        allowedComponents?: string[];
      };
    };
    allowedParents?: string[];
    forbiddenParents?: string[];
  };
  usage?: {
    summary?: string;
    do?: string[];
    dont?: string[];
    relatedComponents?: string[];
  };
  platformNotes?: {
    web?: string;
    ios?: string;
    android?: string;
    macos?: string;
    windows?: string;
  };
  changelog?: {
    version: string;
    date: string;
    changes: string[];
  }[];
}
export interface PropDefinition {
  type: "string" | "boolean" | "number" | "integer" | "enum" | "object" | "array" | "function" | "ref";
  description?: string;
  required?: boolean;
  default?: unknown;
  values?: string[];
  ref?: string;
  itemType?: string;
  tokenMapped?: boolean;
  platforms?: {
    [k: string]: {
      supported?: boolean;
      nativeName?: string;
      notes?: string;
    };
  };
}
